### ISSUE TITLE
error using refactored job runner (using GP package)

### ISSUE THREAD

**Issue by billspat** [krishnanlab/geneplexus_app#214]
the job runner code (mljob/geneplexus.py) was refactored to use the PyGeneplexus package.  It runs fine in docker on laptop.  However when the container is built with Azure container registry and the job is run with this new container in an Azure container instance, it throws the following error.   

Could this be from parameters or files being sent in wrong order?

```
  ound mapping (Symbol) ODAD1 -> ['93233']
Using default logistic regression settings: {'max_iter': 10000, 'solver': 'lbfgs', 'penalty': 'l2', 'C': 1.0}
Traceback (most recent call last):
  
File "runner.py", line 91, in <module>
    html = geneplexus.run_and_render(input_genes, net_type=args.net_type,
 
File "/home/dockeruser/mljob/geneplexus.py", line 142, in run_and_render
    graph, df_probs, df_GO, df_dis, avgps, df_edgelist, df_convert_out, positive_genes = run_model(input_genes, net_type, GSC, features, logger)
  
File "/home/dockeruser/mljob/geneplexus.py", line 113, in run_model
    mdl_weights, df_probs, avgps = gp.fit_and_predict()
 	
File "/home/dockeruser/miniconda/lib/python3.8/site-packages/geneplexus/geneplexus.py", line 279, in fit_and_predict
    self.mdl_weights, self.probs, self.avgps = _geneplexus._run_sl(
 
File "/home/dockeruser/miniconda/lib/python3.8/site-packages/geneplexus/_geneplexus.py", line 117, in _run_sl
    data = util.load_gene_features(file_loc, features, net_type)
 
File "/home/dockeruser/miniconda/lib/python3.8/site-packages/geneplexus/util.py", line 281, in load_gene_features
    return _load_np_file(file_loc, file_name, load_method="npy")
 
File "/home/dockeruser/miniconda/lib/python3.8/site-packages/geneplexus/util.py", line 231, in _load_np_file
    return np.load(file_path)
 
File "/home/dockeruser/miniconda/lib/python3.8/site-packages/numpy/lib/npyio.py", line 430, in load
    return format.read_array(fid, allow_pickle=allow_pickle,
 
File "/home/dockeruser/miniconda/lib/python3.8/site-packages/numpy/lib/format.py", line 786, in read_array
    array.shape = shape

ValueError: cannot reshape array of size 321650656 into shape (19022,19022)

```

**Comment by jacobnewsted** [comment]
Is the backend instance in Azure using the new data format? It is possible the old files are named right but the actual internal's of the numpy pickles are of the new format? We can talk about this later but that is my first idea on this.

**Comment by billspat** [comment]
we suspect the npy files uploaded may be corrupted (dind't finish uploading) since using zenodo is a slow to download.   Will try to re-download the npy files and see if that solves the problem.    

if the downloading is too slow, then log-in to the HPC, download all the data into a shared folder there, then use azcopy to move data from HPC to cloud storage, as we were doing with the previous data.

**Comment by billspat** [comment]
solve the problem with the data files by using a different method for getting the data into Azure storage, since using the package via web app service ssh (which uses zenodo) is too slow/error prone.   Instead, use the package to download the data on another remote linux machine without time out/performance issues (e.g.  MSU hpcc) , `pip install genplexus` then used python to get the files as follows. 
```
# active environment with geneplexus installed 
python
>>> import geneplexus
>>> data_dir = '/path/to/some/dir/geneplexus_data'
>>> geneplexus.download.download_select_data(data_dir, tasks= "all")
>>>exit()
```

then used a function that in the  azuredeploy.sh shell script to `azcopy` from hpcc to azure  ( example uses my home dir)

```
source azure/azuredeploy.sh
az_set_vars dev202205 /mnt/ufs18/home-107/billspat/docs/geneplexus_data

az_copy_hpcc_to_files /mnt/ufs18/home-107/billspat/docs/geneplexus_data/

```

which creates and runs the azcopy command for the folder you specify.  

note the old dir (databackend2) was hard coded in a couple places, and bfe60f89faed9a0a003d955c461176361657060c fixes that.  The name 'geneplexus_data' is now set in az_set_vars and can only be changed if you edit the azuredeploy.sh script.

**Comment by billspat** [comment]
@jacobnewsted the job now runs to completion with correct data uploaded, but there is a new problem: the job page does not render and does not throw an error (it is blank except for menu header and footer)

**Comment by billspat** [comment]
error is in how the file `job_info.json` is created.  

When running the app locally (flask run) and running job without docker: 
```json
{"jobname": "compare-q3tskblb", "net_type": "STRING", "features": "Adjacency", "GSC": "DisGeNet", "avgps": [6.673034945811859, 6.77322767344486, 6.997245559093779], "input_count": 46, "positive_genes": 46, "df_probs_file": "compare-q3tskblb_df_probs.tsv", "df_GO_file": "compare-q3tskblb_df_GO.tsv", "df_dis_file": "compare-q3tskblb_df_dis.tsv", "df_convert_out_subset_file": "compare-q3tskblb_df_convert_out_subset.tsv", "graph_file": "compare-q3tskblb_graph.json", "df_edgelist_file": "compare-q3tskblb_df_edgelist.tsv"}
```

when running with backend docker on azure it's not JSON

```
None
name": "datafix1-fgo0hwba", "net_type": "STRING", "features": "Adjacency", "GSC": "DisGeNet", "avgps": [6.67283578041253, 6.773209401390447, 6.997245559093779], "input_count": 46, "positive_genes": 46, "df_probs_file": "datafix1-fgo0hwba_df_probs.tsv", "df_GO_file": "datafix1-fgo0hwba_df_GO.tsv", "df_dis_file": "datafix1-fgo0hwba_df_dis.tsv", "df_convert_out_subset_file": "datafix1-fgo0hwba_df_convert_out_subset.tsv", "graph_file": "datafix1-fgo0hwba_graph.json", "df_edgelist_file": "datafix1-fgo0hwba_df_edgelist.tsv"}
```

the line in question is https://github.com/krishnanlab/geneplexus_app/blob/0dc1d4e942e633dc28c6151ce248af5ea7ac862a/mljob/model_output.py#L45  (in the branch where we are working on a fix)

**Comment by jacobnewsted** [comment]
Checking my local file when running with docker I get this

```
{"jobname": "docker_job", "net_type": "BioGRID", "features": "Embedding", "GSC": "GO", "avgps": [3.752748312481498, 4.157198019520712, 3.782119255654196], "input_count": 183, "positive_genes": 181, "df_probs_file": "docker_job_df_probs.tsv", "df_GO_file": "docker_job_df_GO.tsv", "df_dis_file": "docker_job_df_dis.tsv", "df_convert_out_subset_file": "docker_job_df_convert_out_subset.tsv", "graph_file": "docker_job_graph.json", "df_edgelist_file": "docker_job_df_edgelist.tsv"}
```

This might be an Azure issue? Let me check further

**Comment by jacobnewsted** [comment]
in the running container instance it gives this error:

```
saving job info to /home/dockeruser/geneplexus-files-dev202205/jobs//datafix1-fgo0hwba/job_info.json 
  adding: datafix1-fgo0hwba/ (stored 0%)
  adding: datafix1-fgo0hwba/datafix1-fgo0hwba.json (deflated 53%)
  adding: datafix1-fgo0hwba/datafix1-fgo0hwba_df_convert_out_subset.tsv (deflated 46%)
  adding: datafix1-fgo0hwba/datafix1-fgo0hwba_df_dis.tsv (deflated 67%)
  adding: datafix1-fgo0hwba/datafix1-fgo0hwba_df_edgelist.tsv (deflated 74%)
  adding: datafix1-fgo0hwba/datafix1-fgo0hwba_df_GO.tsv (deflated 75%)
  adding: datafix1-fgo0hwba/datafix1-fgo0hwba_df_probs.tsv (deflated 63%)
  adding: datafix1-fgo0hwba/datafix1-fgo0hwba_graph.json (deflated 88%)
  adding: datafix1-fgo0hwba/input_genes.txt (deflated 42%)
  adding: datafix1-fgo0hwba/job_info.json (deflated 52%)
  adding: datafix1-fgo0hwba/job_info.json.log
	zip warning:  file size changed while zipping datafix1-fgo0hwba/job_info.json.log
```

So it seems it was either interrupted by something outside of the script or things were happening asynchronously and a write to "job_info.json.log" happened while the zip was happening
